name: first_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  getwidget: ^3.1.1
  image_picker: ^0.8.4+2
  http: ^1.2.0
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.3
  bot_toast: ^4.1.3
  get_it: ^7.7.0
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
